"""add_uri_field_to_task

Revision ID: 085af9a4d465
Revises: 2f874eb3d427
Create Date: 2025-09-15 21:11:02.845481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '085af9a4d465'
down_revision = '2f874eb3d427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invitation_invitee_id', 'invitation', type_='unique')
    op.add_column('task', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'uri')
    op.create_unique_constraint('uq_invitation_invitee_id', 'invitation', ['invitee_id'])
    # ### end Alembic commands ###
