"""add_service_account_table_id

Revision ID: 0fedf2e4130b
Revises: a4d36ff1bbf5
Create Date: 2025-10-24 15:26:05.943358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0fedf2e4130b'
down_revision = 'a4d36ff1bbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_account', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'service_account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_account', type_='foreignkey')
    op.drop_column('service_account', 'user_id')
    # ### end Alembic commands ###
