"""change_trigger_event_to_string

Revision ID: 23b8a4c76fb8
Revises: 4e3f3a897f02
Create Date: 2025-09-16 11:29:20.924005

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23b8a4c76fb8'
down_revision = '4e3f3a897f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogconfig', 'trigger_event',
               existing_type=postgresql.ENUM('APP_LAUNCH', 'ENTER_STORE_PAGE', 'ENTER_PRODUCT_PAGE', 'USER_LOGIN', 'ORDER_COMPLETE', 'CUSTOM', name='dialogtriggerevent'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogconfig', 'trigger_event',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('APP_LAUNCH', 'ENTER_STORE_PAGE', 'ENTER_PRODUCT_PAGE', 'USER_LOGIN', 'ORDER_COMPLETE', 'CUSTOM', name='dialogtriggerevent'),
               existing_nullable=False)
    # ### end Alembic commands ###
