"""Add hot search table

Revision ID: 261076d43496
Revises: 79efb55b196b
Create Date: 2025-08-21 01:34:27.051582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '261076d43496'
down_revision = '79efb55b196b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotsearch',
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotsearch')
    # ### end Alembic commands ###
