"""update_cart_product_model

Revision ID: 2d766b6ea5d1
Revises: 1cea98f1423c
Create Date: 2025-09-08 14:29:00.583723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d766b6ea5d1'
down_revision = '1cea98f1423c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
