"""add_invitation_system

Revision ID: 2f874eb3d427
Revises: c77d9ac10465
Create Date: 2025-09-15 17:12:57.682173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f874eb3d427'
down_revision = 'c77d9ac10465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先添加可空的invite_code列
    op.add_column('user', sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    
    # 2. 为现有用户生成邀请码
    from app.utils import generate_invite_code
    import random
    
    # 获取所有现有用户
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM \"user\""))
    user_ids = [row[0] for row in result]
    
    # 为每个用户生成唯一邀请码
    used_codes = set()
    for user_id in user_ids:
        # 生成唯一邀请码
        while True:
            invite_code = generate_invite_code()
            if invite_code not in used_codes:
                # 检查数据库中是否已存在
                check_result = connection.execute(
                    sa.text("SELECT COUNT(*) FROM \"user\" WHERE invite_code = :code"),
                    {"code": invite_code}
                )
                if check_result.scalar() == 0:
                    used_codes.add(invite_code)
                    break
        
        # 更新用户记录
        connection.execute(
            sa.text("UPDATE \"user\" SET invite_code = :code WHERE id = :user_id"),
            {"code": invite_code, "user_id": user_id}
        )
    
    # 3. 将invite_code列设置为非空
    op.alter_column('user', 'invite_code', nullable=False)
    
    # 4. 创建唯一索引
    op.create_index(op.f('ix_user_invite_code'), 'user', ['invite_code'], unique=True)
    
    # 5. 创建邀请表
    op.create_table('invitation',
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('reward_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_invitation_invitee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invite_code'), table_name='user')
    op.drop_column('user', 'invite_code')
    op.drop_table('invitation')
    # ### end Alembic commands ###
