"""add_dialog_config_system

Revision ID: 4e3f3a897f02
Revises: 085af9a4d465
Create Date: 2025-09-16 10:01:29.070960

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e3f3a897f02'
down_revision = '085af9a4d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogconfig',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.Enum('APP_LAUNCH', 'ENTER_STORE_PAGE', 'ENTER_PRODUCT_PAGE', 'USER_LOGIN', 'ORDER_COMPLETE', 'CUSTOM', name='dialogtriggerevent'), nullable=False),
    sa.Column('dialog_type', sa.Enum('PROMOTION_BANNER', 'NOTIFICATION_POPUP', 'CONFIRMATION_DIALOG', 'INFO_MODAL', 'CUSTOM', name='dialogtype'), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buttons', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.Enum('ALL_USERS', 'NEW_USERS', 'VIP_USERS', 'SPECIFIC_USERS', name='targetaudience'), nullable=False),
    sa.Column('display_frequency', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'ALWAYS', name='displayfrequency'), nullable=False),
    sa.Column('max_display_count', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogdisplayrecord',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dialog_config_id', sa.Uuid(), nullable=False),
    sa.Column('display_count', sa.Integer(), nullable=False),
    sa.Column('last_displayed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_config_id'], ['dialogconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogdisplayrecord')
    op.drop_table('dialogconfig')
    # ### end Alembic commands ###
