"""add_points_mall_tables

Revision ID: 528276097537
Revises: 08aa112b8d89
Create Date: 2025-11-03 16:26:36.647817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '528276097537'
down_revision = '08aa112b8d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_product_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category_type', sa.Enum('DATA_PACKAGE', 'MEMBERSHIP_CARD', 'COUPON', 'MOVIE_TICKET', 'PHYSICAL_PRODUCT', name='pointsproductcategorytype'), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('exchanged_quantity', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('max_exchange_per_user', sa.Integer(), nullable=False),
    sa.Column('min_points_balance', sa.Integer(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('detail_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['points_product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_product_exchange',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('points_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ISSUED', 'USED', 'EXPIRED', 'REFUNDED', 'CANCELLED', name='exchangestatus'), nullable=False),
    sa.Column('exchange_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['points_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_product_exchange_exchange_code'), 'points_product_exchange', ['exchange_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_product_exchange_exchange_code'), table_name='points_product_exchange')
    op.drop_table('points_product_exchange')
    op.drop_table('points_product')
    op.drop_table('points_product_category')
    # ### end Alembic commands ###
