"""add_blind_box_lottery_system

Revision ID: 641f61ece900
Revises: 44881a6c47aa
Create Date: 2025-12-03 22:29:41.541349

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '641f61ece900'
down_revision = '44881a6c47aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_template',
    sa.Column('prize_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prize_type', sa.Enum('BREAD_CHAMPION', 'VIDEO_MEMBERSHIP', 'MUSIC_MEMBERSHIP', 'POINTS', 'COUPON', 'THANK_YOU', name='blindboxprizetype'), nullable=False),
    sa.Column('prize_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('redemption_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prize_template_prize_code'), 'prize_template', ['prize_code'], unique=True)
    op.create_table('recharge_order',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recharge_type', sa.Enum('MOBILE', 'DATA', name='rechargetype'), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', name='rechargeorderstatus'), nullable=False),
    sa.Column('business_district_id', sa.Uuid(), nullable=True),
    sa.Column('user_latitude', sa.Float(), nullable=True),
    sa.Column('user_longitude', sa.Float(), nullable=True),
    sa.Column('is_eligible_for_prize', sa.Boolean(), nullable=False),
    sa.Column('order_no', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_district_id'], ['businessdistrict.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_order_order_no'), 'recharge_order', ['order_no'], unique=True)
    op.create_table('user_blind_box',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recharge_order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('UNOPENED', 'OPENED', 'EXPIRED', name='blindboxstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recharge_order_id'], ['recharge_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blind_box_user_prize',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('blind_box_id', sa.Uuid(), nullable=False),
    sa.Column('prize_template_id', sa.Uuid(), nullable=False),
    sa.Column('redemption_status', sa.Enum('UNREDEEMED', 'REDEEMED', 'EXPIRED', 'USED', name='prizeredemptionstatus'), nullable=False),
    sa.Column('redemption_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blind_box_id'], ['user_blind_box.id'], ),
    sa.ForeignKeyConstraint(['prize_template_id'], ['prize_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blind_box_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blind_box_user_prize')
    op.drop_table('user_blind_box')
    op.drop_index(op.f('ix_recharge_order_order_no'), table_name='recharge_order')
    op.drop_table('recharge_order')
    op.drop_index(op.f('ix_prize_template_prize_code'), table_name='prize_template')
    op.drop_table('prize_template')
    # ### end Alembic commands ###
