"""add_points_redeemed_to_user

Revision ID: 67f69c6d17c3
Revises: fd159a5e02ad
Create Date: 2025-11-25 11:15:15.760688

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67f69c6d17c3'
down_revision = 'fd159a5e02ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加积分兑换累计字段，分两步处理以避免NOT NULL约束错误
    op.add_column('user', sa.Column('points_redeemed', sa.Integer(), nullable=True))
    # 设置现有用户的累计兑换积分为0
    op.execute("UPDATE \"user\" SET points_redeemed = 0 WHERE points_redeemed IS NULL")
    # 将字段设置为非空
    op.alter_column('user', 'points_redeemed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points_redeemed')
    # ### end Alembic commands ###
