"""update_points_mall_tables_label

Revision ID: 7b62b73f82c6
Revises: 528276097537
Create Date: 2025-11-05 14:44:02.951200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7b62b73f82c6'
down_revision = '528276097537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先创建枚举类型（使用小写值，与模型定义一致）
    points_product_label_enum = postgresql.ENUM(
        'popular_recommend',
        'guess_you_like',
        'fresh_goods',
        'hot_sale',
        'limited_time',
        'new_arrival',
        'best_value',
        'exclusive',
        name='pointsproductlabel',
        create_type=False
    )
    points_product_label_enum.create(op.get_bind(), checkfirst=True)
    
    # 然后添加列
    op.add_column('points_product', sa.Column('label', points_product_label_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_product', 'label')
    # 删除枚举类型
    op.execute("DROP TYPE IF EXISTS pointsproductlabel")
    # ### end Alembic commands ###
