"""remove_probability_field_from_lottery_prizes

Revision ID: 82796a21e678
Revises: fce249d7df14
Create Date: 2025-09-19 16:22:21.756624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82796a21e678'
down_revision = 'fce249d7df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteryprize', 'probability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteryprize', sa.Column('probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
