"""add_product_description_to_product_detail

Revision ID: 922b8e68ae7f
Revises: 978835e41489
Create Date: 2025-09-03 11:54:20.232943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '922b8e68ae7f'
down_revision = '978835e41489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdetail', sa.Column('product_description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productdetail', 'product_description')
    # ### end Alembic commands ###
