"""add_product_detail_table

Revision ID: 978835e41489
Revises: 1f93854cf1ac
Create Date: 2025-09-02 10:57:51.366322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '978835e41489'
down_revision = '1f93854cf1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productdetail',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('main_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('gallery_image_urls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attributes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variants', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('gift_data_package', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gift_coupon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gift_voice_package', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gift_membership', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productdetail')
    # ### end Alembic commands ###
