"""update payment add none

Revision ID: 9c97d4d3cb7d
Revises: f56b7276577c
Create Date: 2025-09-11 10:28:32.868603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c97d4d3cb7d'
down_revision = 'f56b7276577c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'payment_method',
               existing_type=postgresql.ENUM('CREDIT_CARD', 'ALIPAY', 'WECHAT_PAY', 'PAYPAL', 'BANK_TRANSFER', name='paymentmethod'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'payment_method',
               existing_type=postgresql.ENUM('CREDIT_CARD', 'ALIPAY', 'WECHAT_PAY', 'PAYPAL', 'BANK_TRANSFER', name='paymentmethod'),
               nullable=False)
    # ### end Alembic commands ###
