"""update_coupon_detailed

Revision ID: a9a46d2cb13a
Revises: e1e469617504
Create Date: 2025-09-06 12:19:08.638186

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a9a46d2cb13a'
down_revision = 'e1e469617504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercoupon', sa.Column('detailed_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercoupon', 'detailed_instructions')
    # ### end Alembic commands ###
