"""update order list model

Revision ID: aa074224a662
Revises: 9c97d4d3cb7d
Create Date: 2025-09-11 17:59:08.678830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa074224a662'
down_revision = '9c97d4d3cb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
