"""add_data_packages_and_membership_benefits_tables

Revision ID: aaec0eb5e688
Revises: ce077c05a373
Create Date: 2025-09-04 17:54:49.818309

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aaec0eb5e688'
down_revision = 'ce077c05a373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapackage',
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('package_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_mb', sa.Integer(), nullable=False),
    sa.Column('used_mb', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membershipbenefit',
    sa.Column('benefit_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('total_duration_days', sa.Integer(), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ui_config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membershipbenefit')
    op.drop_table('datapackage')
    # ### end Alembic commands ###
