"""add_pickup_code_fields_to_order

Revision ID: ba41ab385575
Revises: d2b8f7995a87
Create Date: 2025-09-12 20:38:03.784950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba41ab385575'
down_revision = 'd2b8f7995a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pickup_code', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True))
    op.add_column('order', sa.Column('pickup_code_generated_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('pickup_code_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'pickup_code_verified_at')
    op.drop_column('order', 'pickup_code_generated_at')
    op.drop_column('order', 'pickup_code')
    # ### end Alembic commands ###
