"""add_button_text_to_task

Revision ID: c77d9ac10465
Revises: 5ec37b704793
Create Date: 2025-09-14 11:50:05.808275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c77d9ac10465'
down_revision = '5ec37b704793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('button_text', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'button_text')
    # ### end Alembic commands ###
