"""add_product_usege_rules

Revision ID: ce077c05a373
Revises: 922b8e68ae7f
Create Date: 2025-09-03 21:10:00.585515

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce077c05a373'
down_revision = '922b8e68ae7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdetail', sa.Column('usage_rules', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productdetail', 'usage_rules')
    # ### end Alembic commands ###
