"""update order: Add is_delete

Revision ID: d2b8f7995a87
Revises: aa074224a662
Create Date: 2025-09-12 16:29:48.446451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2b8f7995a87'
down_revision = 'aa074224a662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加字段，允许为null
    op.add_column('order', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # 为现有数据设置默认值
    op.execute("UPDATE \"order\" SET is_deleted = false WHERE is_deleted IS NULL")
    
    # 然后将字段设置为 NOT NULL
    op.alter_column('order', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'deleted_at')
    op.drop_column('order', 'is_deleted')
    # ### end Alembic commands ###
