"""add_upons_table

Revision ID: e1e469617504
Revises: aaec0eb5e688
Create Date: 2025-09-06 11:36:07.585589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1e469617504'
down_revision = 'aaec0eb5e688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupontemplate',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('coupon_type', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_spend', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage_scope_desc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('issued_quantity', sa.Integer(), nullable=False),
    sa.Column('validity_type', sa.Integer(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=True),
    sa.Column('fixed_start_time', sa.DateTime(), nullable=True),
    sa.Column('fixed_end_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usercoupon',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('coupon_type', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_spend', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage_scope_desc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('used_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('coupon_template_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_template_id'], ['coupontemplate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercoupon')
    op.drop_table('coupontemplate')
    # ### end Alembic commands ###
