"""Remove payment_method from order creation, add PaymentRequest model

Revision ID: f56b7276577c
Revises: 3e87350f6feb
Create Date: 2025-09-11 10:10:55.570035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f56b7276577c'
down_revision = '3e87350f6feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
