"""add_lottery_system

Revision ID: fce249d7df14
Revises: 23b8a4c76fb8
Create Date: 2025-09-19 15:17:49.716884

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fce249d7df14'
down_revision = '23b8a4c76fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteryactivity',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED', 'CANCELLED', name='lotteryactivitystatus'), nullable=False),
    sa.Column('max_draws_per_user', sa.Integer(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotteryprize',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('prize_type', sa.Enum('POINTS', 'VIRTUAL', 'PHYSICAL', 'THANK_YOU', name='prizetype'), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['lotteryactivity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotteryrecord',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('prize_id', sa.Uuid(), nullable=False),
    sa.Column('prize_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prize_type_snapshot', sa.Enum('POINTS', 'VIRTUAL', 'PHYSICAL', 'THANK_YOU', name='prizetype'), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['lotteryactivity.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['lotteryprize.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprize',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prize_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', 'CANCELLED', name='userprizestatus'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prize_id'], ['lotteryprize.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprize')
    op.drop_table('lotteryrecord')
    op.drop_table('lotteryprize')
    op.drop_table('lotteryactivity')
    # ### end Alembic commands ###
